services:

  user-service:
    build: ../PS-Back-UsersTeachers
    container_name: user-service
    ports:
      - "8081:8081"
    networks:
      - user-network
    depends_on:
      mysql-db:
        condition: service_healthy
    restart: on-failure

  mysql-db:
    image: mysql:8.0
    container_name: users_db-mysql
    environment:
      MYSQL_DATABASE: users_db
      MYSQL_USER: user_app
      MYSQL_PASSWORD: user_pass
      MYSQL_ROOT_PASSWORD: root_pass
    ports:
      - "3307:3306"
    expose:
      - "3307"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_pass"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - user-network

volumes:
  mysql-data:

networks:
  user-network:
    external: true
    name: shared-network