package org.utn.tup.ps.Enum;

public enum Course {
    KINDERGARTEN, FIRST_GRADE, SECOND_GRADE, THIRD_GRADE, FOURTH_GRADE, FIFTH_GRADE, SIXTH_GRADE,
    FIRST_YEAR, SECOND_YEAR, THIRD_YEAR, FOURTH_YEAR, FIFTH_YEAR, SIXTH_YEAR, UNIVERSITY;
}
